apiVersion: v1
kind: Pod
metadata:
  name: kaniko-test
spec:
  containers:
    - name: kaniko-test
      image: registry.cn-hangzhou.aliyuncs.com/tekton-pipelines/executor:latest
      args:
        - --dockerfile=/opt/hello/Dockerfile
        - --context=/opt/hello
        - --cache=true
        - --destination=fc277073030/hello:v1.0
        - --cache-dir=/cache
      volumeMounts:
        - name: context-data
          mountPath: /opt/hello
        - name: docker-config
          mountPath: /kaniko/.docker/
        - name: kaniko-cache
          mountPath: /cache
  restartPolicy: Never
  volumes:
    - name: context-data
      configMap:
        name: dockerfile-cm
    - name: docker-config
      secret:
        secretName: kaniko-secret
#      configMap:
#        name: docker-config
    - name: kaniko-cache
      persistentVolumeClaim:
        claimName: kaniko-cache-claim
