apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
    - name: kaniko
      image: registry.cn-hangzhou.aliyuncs.com/tekton-pipelines/executor:latest
      args:
        - --dockerfile=/flask-demo/Dockerfile
        - --context=/flask-demo
        - --destination=fc277073030/flask-demo:v3.0
#        - --cache=true
#        - --cache-dir=/cache
      volumeMounts:
        - name: context-data
          mountPath: /flask-demo
        - name: kaniko-secret
          mountPath: /kaniko/.docker/
#        - name: kaniko-cache
#          mountPath: /cache
  restartPolicy: Never
  volumes:
    - name: context-data
      persistentVolumeClaim:
        claimName: kaniko-cache-claim
    - name: kaniko-secret
      secret:
        secretName: kaniko-secret
#    - name: kaniko-cache
#      persistentVolumeClaim:
#        claimName: kaniko-cache-claim

