apiVersion: v1
kind: PersistentVolume
metadata:
  name: Dockerfile
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: alicloud-nas
  hostPath:
    path: "/kaniko"
